<?php

namespace Elshaden\ModalPopup;

use Closure;
use Elshaden\ModalPopup\Http\Livewire\PopupCreate;
use Elshaden\ModalPopup\Http\Livewire\PopUpsIndex;
use Livewire\Livewire;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Elshaden\ModalPopup\Commands\ModalPopupCommand;

class ModalPopupServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('modal-popup')
            ->hasConfigFile()
            ->hasViews()
            ->hasMigration('create_modal_popup_table')
           ;
    }


    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

    }

    public function bootingPackage()
    {
        parent::bootingPackage(); // TODO: Change the autogenerated stub
        Livewire::component('popup-index', PopUpsIndex::class);
        Livewire::component('popup-create', PopupCreate::class);

    }
}
